export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const PERSIST_USER_REQUEST = "PERSIST_USER_REQUEST";
export const PERSIST_USER_SUCCESS = "PERSIST_USER_SUCCESS";
export const PERSIST_USER_FAILURE = "PERSIST_USER_FAILURE";

export const CLEAR_FORM_ERROR = "CLEAR_FORM_ERROR";
export const PERSIST_USER = "PERSIST_USER"